[phases.setup]
nixPkgs = ['nodejs_22', 'corepack', 'openssl']
cmds = ['bash .nixpacks/setup.sh']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = [
  'pnpm db:generate',
  'pnpm --filter @beteseb/backend exec prisma migrate deploy',
  'pnpm build'
]

[start]
cmd = 'pnpm start'
