[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
    "npx prisma generate --schema=apps/backend/prisma/schema.prisma",
    "npm run build"
]

[start]
cmd = "cd apps/backend && npx prisma migrate deploy && node dist/index.js"
